---
   - hosts: database
     become: true
     tasks:
       - name: install tools
         yum: name={{item}} state=present update_cache=yes
         with_items:
            - MySQL-python

       - name: install mysql-server
         yum: name=mysql-community-server state=present update_cache=yes

       - name: ensure mysql started
         service: name=mysqld state=started enabled=yes

       - name: delete all lines that start with bind-address except for the one with 0.0.0.0
         lineinfile: dest=/etc/my.cnf regexp='^bind-address (?!\= 0.0.0.0)' state=absent
         notify: restart mysqld

       - name: ensure mysql is listening on all ports
         lineinfile: dest=/etc/my.cnf insertafter='^#?\[mysqld\]' line="bind-address = 0.0.0.0"
         notify: restart mysqld

       - name: create demo database
         mysql_db: name=demo state=present

       - name: create demo user
         mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

     handlers:
       - name: restart mysqld
         service: name=mysqld state=restarted 
